# Generated by Django 4.0.4 on 2022-05-29 00:43

from django.db import migrations
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_alter_match_opponent_deck"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opponentdeck",
            old_name="name",
            new_name="archetype",
        ),
        migrations.AlterField(
            model_name="deck",
            name="maindeck",
            field=tracker.models.CardListManyToManyField(
                related_name="in_maindeck",
                through="tracker.MaindeckPart",
                to="tracker.card",
            ),
        ),
        migrations.AlterField(
            model_name="deck",
            name="sideboard",
            field=tracker.models.CardListManyToManyField(
                related_name="in_sideboard",
                through="tracker.SideboardPart",
                to="tracker.card",
            ),
        ),
    ]
