# Generated by Django 4.0.4 on 2022-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='format',
            field=models.TextField(choices=[('M', 'Modern'), ('P', 'Pioneer'), ('L', 'Legacy')], default=''),
            preserve_default=False,
        ),
    ]
