# Generated by Django 4.0.4 on 2022-06-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_archetype_deck_archetype_opponentdeck__archetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opponentdeck',
            name='archetype',
        ),
    ]
