# Generated by Django 4.0.4 on 2022-06-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_opponentdeck_archetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opponentdeck',
            old_name='_archetype',
            new_name='archetype',
        ),
    ]
