# Generated by Django 4.0.4 on 2022-07-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_game_game_number_alter_game_opponent_mulligans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='maindeck',
            field=models.ManyToManyField(related_name='in_maindeck', through='tracker.MaindeckPart', to='tracker.card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='sideboard',
            field=models.ManyToManyField(related_name='in_sideboard', through='tracker.SideboardPart', to='tracker.card'),
        ),
    ]
