# Generated by Django 4.0.4 on 2022-05-23 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SideboardPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.opponent')),
                ('opponent_deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_opponent', to='tracker.deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('player_deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_player', to='tracker.deck')),
            ],
        ),
        migrations.CreateModel(
            name='MaindeckPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_win', models.BooleanField()),
                ('player_mulligans', models.IntegerField()),
                ('opponent_mulligans', models.IntegerField()),
                ('game_notes', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.match')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='maindeck',
            field=models.ManyToManyField(related_name='in_maindeck', through='tracker.MaindeckPart', to='tracker.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deck',
            name='sideboard',
            field=models.ManyToManyField(related_name='in_sideboard', through='tracker.SideboardPart', to='tracker.card'),
        ),
    ]
