# Generated by Django 4.0.4 on 2022-05-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_delete_archetype_alter_deck_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="tracker.event",
            ),
            preserve_default=False,
        ),
    ]
