# Generated by Django 4.0.4 on 2022-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_match_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_notes',
            field=models.TextField(null=True),
        ),
    ]
