# Generated by Django 4.0.4 on 2022-05-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_match_opponent_deck_1_match_opponent_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opponent_deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tracker.opponentdeck'),
            preserve_default=False,
        ),
    ]
