# Generated by Django 4.0.4 on 2022-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_opponentdeck_archetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_number',
            field=models.IntegerField(choices=[(1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_mulligans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_mulligans',
            field=models.IntegerField(default=0),
        ),
    ]
